name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
          architecture: 'x64'

      - name: Run recursive autoflake
        run: >
          pip install autoflake ;
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports --recursive .
      - name: Linting
        uses: py-actions/flake8@v2
        with:
          ignore: "E501,E741,W605,E265,E226,W504,W291,E261,W293,E303,E231,E203,E302,E251,E127,E124,E211,E305,E128"

      - name: Run autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --recursive --in-place --aggressive --aggressive .

      - name: Update channels 
        run: >
          pip install -r requirements.txt ;
          python generate.py 
        env:
          PLAYTV_UNIFI_USER_ID: ${{ secrets.PLAYTV_UNIFI_USER_ID }}
          PLAYTV_UNIFI_PASSWORD: ${{ secrets.PLAYTV_UNIFI_PASSWORD }}
          PLAYTV_UNIFI_DEVICE_ID: ${{ secrets.PLAYTV_UNIFI_DEVICE_ID }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated change

  test:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
          architecture: 'x64'
          
      - name: Run tests
        run: >
          pip install -r requirements.txt &&
          python generate.py &&
          python tests/main.py &&
          xmllint --debug tv.xml
        env:
          PLAYTV_UNIFI_USER_ID: ${{ secrets.PLAYTV_UNIFI_USER_ID }}
          PLAYTV_UNIFI_PASSWORD: ${{ secrets.PLAYTV_UNIFI_PASSWORD }}
          PLAYTV_UNIFI_DEVICE_ID: ${{ secrets.PLAYTV_UNIFI_DEVICE_ID }}
